#!/usr/bin/env node
/**
 * QCC Script Factory — Generate, deploy, and queue experiment scripts
 *
 * Provides parameterized Python script templates for the four core experiment
 * types (fillsim_sweep, strategy_signal_gen, model_training, analysis), plus
 * helpers to deploy scripts via SFTP and enqueue them in the research_queue.
 *
 * Usage (from orchestrator or MCP server):
 *
 *   const factory = require('./script_factory');
 *   factory.init(db);                          // pass the QCCDatabase instance
 *
 *   // Generate script text only
 *   const py = factory.generateScript('fillsim_sweep', { dates: ['2025-01-06'], tp_ticks: [3,4,5] });
 *
 *   // Full end-to-end: generate → deploy via SFTP → enqueue
 *   const expId = await factory.createAndQueueExperiment(
 *     'fillsim_sweep',
 *     { dates: ['2025-01-06'], tp_ticks: [3,4,5] },
 *     'jupiter',
 *     3   // priority (lower = sooner)
 *   );
 *
 *   // Follow-up suggestions after a completed experiment
 *   const suggestions = factory.suggestFollowUp(completedExperiment, parsedResult);
 *   for (const s of suggestions) {
 *     await factory.createAndQueueExperiment(s.template, s.params, s.node, s.priority, s.dependsOn);
 *   }
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ─── Paths ─────────────────────────────────────────────────────────────────

const BASE_DIR       = path.join(__dirname, '..');
const LOCAL_SCRIPTS  = path.join(BASE_DIR, 'scripts');          // teleclaude/scripts/
const SERVERS_CONFIG = path.join(BASE_DIR, 'config', 'remote_servers.json');
const SSH_EXEC_PY    = path.join(BASE_DIR, 'utils', 'ssh_exec.py');

// Remote script staging dir — relative to the node's Lvl3Quant root
const REMOTE_SCRIPTS_SUBDIR = 'scripts';

// Ensure local scripts staging dir exists
if (!fs.existsSync(LOCAL_SCRIPTS)) fs.mkdirSync(LOCAL_SCRIPTS, { recursive: true });

// ─── Module state ──────────────────────────────────────────────────────────

let _db = null;   // QCCDatabase instance, set via init()

/**
 * Bind the factory to a QCCDatabase instance.
 * Must be called before createAndQueueExperiment / deployScript.
 */
function init(db) {
  _db = db;
}

// ─── Template helpers ──────────────────────────────────────────────────────

/**
 * Fill {{key}} placeholders in a template string with values from a params object.
 * Arrays are serialised to Python list literals.
 * Objects are serialised to Python dict literals.
 * Undefined/null values fall back to the placeholder default if one is embedded
 * as {{key|default}}, or to 'None'.
 */
function fillTemplate(template, params) {
  return template.replace(/\{\{(\w+)(?:\|([^}]*))?\}\}/g, (match, key, def) => {
    const raw = params[key] !== undefined && params[key] !== null ? params[key] : def;
    if (raw === undefined || raw === null) return 'None';

    if (Array.isArray(raw)) {
      const items = raw.map(v => (typeof v === 'string' ? `"${v}"` : String(v)));
      return `[${items.join(', ')}]`;
    }
    if (typeof raw === 'object') return JSON.stringify(raw);
    if (typeof raw === 'string') return raw;   // caller controls quoting in template
    return String(raw);
  });
}

// ─── TEMPLATES ─────────────────────────────────────────────────────────────
//
// Placeholders:
//   {{param}}           — required, renders as bare value (no extra quotes added)
//   {{param|default}}   — optional with fallback
//
// Each template prints a JSON line starting with "RESULT:" so the orchestrator's
// parseExperimentOutput() can harvest metrics automatically.
// ───────────────────────────────────────────────────────────────────────────

const TEMPLATES = {};

// ─── 1. fillsim_sweep ──────────────────────────────────────────────────────
TEMPLATES.fillsim_sweep = `#!/usr/bin/env python3
"""
Fill-sim sweep — generated by QCC Script Factory
Template: fillsim_sweep
Params:
  dates          : list of YYYYMMDD strings to sweep over
  tp_ticks       : list of take-profit tick values
  sl_ticks       : list of stop-loss tick values
  trailing_ticks : list of trailing-stop tick values  (0 = disabled)
  hold_ms        : list of hold durations in milliseconds
  signal_sources : list of NPZ prediction file paths (absolute) or model names
  time_decay     : comma-separated time-decay config string, e.g. "linear,0.5,300"
  fill_sim_cli   : absolute path to fill_sim_cli binary on this node
  output_dir     : directory to write per-run result JSON files
  min_signal     : minimum signal threshold for entry (default 0.0)
"""
import subprocess, json, sys, os, itertools
from datetime import datetime

DATES          = {{dates}}
TP_TICKS       = {{tp_ticks|[3, 4, 5]}}
SL_TICKS       = {{sl_ticks|[2, 3, 4]}}
TRAILING_TICKS = {{trailing_ticks|[0]}}
HOLD_MS        = {{hold_ms|[10000]}}
SIGNAL_SOURCES = {{signal_sources|[]}}
TIME_DECAY     = "{{time_decay|none}}"
FILL_SIM_CLI   = "{{fill_sim_cli}}"
OUTPUT_DIR     = "{{output_dir|.}}"
MIN_SIGNAL     = {{min_signal|0.0}}

os.makedirs(OUTPUT_DIR, exist_ok=True)

all_runs = []
errors   = []

# If no signal sources given, run without --signal-file (uses built-in uniform random)
sources = SIGNAL_SOURCES if SIGNAL_SOURCES else [None]

for date, tp, sl, trail, hold, src in itertools.product(
    DATES, TP_TICKS, SL_TICKS, TRAILING_TICKS, HOLD_MS, sources
):
    tag = f"{date}_tp{tp}_sl{sl}_trail{trail}_hold{hold}"
    if src:
        src_label = os.path.splitext(os.path.basename(str(src)))[0]
        tag += f"_{src_label}"

    cmd = [
        FILL_SIM_CLI,
        "--date", str(date),
        "--tp-ticks", str(tp),
        "--sl-ticks", str(sl),
        "--hold-ms", str(hold),
        "--min-signal", str(MIN_SIGNAL),
        "--json-output",
    ]
    if trail and trail > 0:
        cmd += ["--trailing-ticks", str(trail)]
    if src:
        cmd += ["--signal-file", str(src)]
    if TIME_DECAY and TIME_DECAY.lower() not in ("none", ""):
        cmd += ["--time-decay", TIME_DECAY]

    print(f"[fillsim] Running {tag} ...", flush=True)
    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=300
        )
        if proc.returncode != 0:
            errors.append({"tag": tag, "error": proc.stderr[-500:]})
            print(f"  ERROR: {proc.stderr[-200:]}", flush=True)
            continue

        try:
            result = json.loads(proc.stdout.strip())
        except json.JSONDecodeError:
            # Some versions print multiple lines; take the last JSON object
            for line in reversed(proc.stdout.strip().splitlines()):
                try:
                    result = json.loads(line)
                    break
                except Exception:
                    pass
            else:
                errors.append({"tag": tag, "error": "no JSON in stdout"})
                continue

        result["mbo_date"]    = str(date)
        result["config_name"] = tag
        result["tp_ticks"]    = tp
        result["sl_ticks"]    = sl
        result["trailing_ticks"] = trail
        result["hold_ms"]     = hold
        result["signal_source"] = str(src) if src else None

        all_runs.append(result)

        # Quick per-run summary
        pnl  = result.get("total_pnl", result.get("pnl", "N/A"))
        fills = result.get("total_filled", result.get("filled", "N/A"))
        rate = result.get("fill_rate", "N/A")
        print(f"  pnl={pnl}  filled={fills}  fill_rate={rate}", flush=True)

        # Save individual run
        run_file = os.path.join(OUTPUT_DIR, f"{tag}.json")
        with open(run_file, "w") as f:
            json.dump(result, f, indent=2)

    except subprocess.TimeoutExpired:
        errors.append({"tag": tag, "error": "timeout after 300s"})
        print(f"  TIMEOUT", flush=True)
    except Exception as exc:
        errors.append({"tag": tag, "error": str(exc)})
        print(f"  EXCEPTION: {exc}", flush=True)

# Aggregate summary
summary = {
    "runs":        all_runs,
    "total_runs":  len(all_runs),
    "errors":      len(errors),
    "dates":       DATES,
    "pnl":         round(sum(r.get("total_pnl", r.get("pnl", 0)) for r in all_runs), 4) if all_runs else None,
    "trades":      sum(r.get("total_trades", r.get("trades", 0)) for r in all_runs) if all_runs else None,
    "fill_rate":   round(
        sum(r.get("fill_rate", 0) for r in all_runs) / len(all_runs), 4
    ) if all_runs else None,
}
print(f"RESULT: {json.dumps(summary)}", flush=True)
print(f"[fillsim] Done. {len(all_runs)} runs completed, {len(errors)} errors.", flush=True)
`;

// ─── 2. strategy_signal_gen ────────────────────────────────────────────────
TEMPLATES.strategy_signal_gen = `#!/usr/bin/env python3
"""
Strategy signal generator — generated by QCC Script Factory
Template: strategy_signal_gen
Generates trading signals from a configurable strategy and saves as NPZ.

Params:
  strategy       : strategy type — "book_imbalance" | "momentum" | "vwap_reversion" | "combined"
  data_dir       : directory containing MBO/book data (tick files, NPZ, etc.)
  output_path    : output NPZ file path (absolute)
  dates          : list of YYYYMMDD strings to generate signals for
  lookback_bars  : number of bars for momentum/smoothing window
  imbalance_depth: order book depth levels for imbalance calculation
  momentum_window: bars for momentum calculation
  min_signal     : minimum absolute signal value to keep (trim noise)
  normalize      : normalise signals to [-1, 1] range
  side           : "both" | "long_only" | "short_only"
"""
import numpy as np
import os, json, sys
from pathlib import Path

STRATEGY        = "{{strategy|book_imbalance}}"
DATA_DIR        = Path("{{data_dir}}")
OUTPUT_PATH     = Path("{{output_path}}")
DATES           = {{dates}}
LOOKBACK_BARS   = {{lookback_bars|20}}
IMBALANCE_DEPTH = {{imbalance_depth|5}}
MOMENTUM_WINDOW = {{momentum_window|10}}
MIN_SIGNAL      = {{min_signal|0.01}}
NORMALIZE       = {{normalize|True}}
SIDE            = "{{side|both}}"

os.makedirs(OUTPUT_PATH.parent, exist_ok=True)

def calc_book_imbalance(bids, asks, depth):
    """Compute bid-ask volume imbalance across depth levels."""
    bid_vol = np.sum(bids[:depth, 1]) if bids.shape[0] >= depth else np.sum(bids[:, 1])
    ask_vol = np.sum(asks[:depth, 1]) if asks.shape[0] >= depth else np.sum(asks[:, 1])
    total = bid_vol + ask_vol
    if total == 0:
        return 0.0
    return float((bid_vol - ask_vol) / total)

def calc_momentum(prices, window):
    """Simple price momentum: (price[t] - price[t-window]) / price[t-window]."""
    if len(prices) < window + 1:
        return 0.0
    return float((prices[-1] - prices[-window]) / (prices[-window] + 1e-8))

def calc_vwap_reversion(prices, volumes, window):
    """VWAP reversion signal: z-score of (price - VWAP)."""
    if len(prices) < window:
        return 0.0
    w_prices = np.array(prices[-window:], dtype=float)
    w_vols   = np.array(volumes[-window:], dtype=float)
    total_vol = np.sum(w_vols)
    if total_vol == 0:
        return 0.0
    vwap = np.sum(w_prices * w_vols) / total_vol
    std  = np.std(w_prices) + 1e-8
    return float(-(prices[-1] - vwap) / std)  # negative = fade the deviation

all_signals   = []
all_timestamps = []
total_signals = 0

for date in DATES:
    # Look for the date's data file — supports several naming conventions
    candidates = [
        DATA_DIR / f"{date}.npz",
        DATA_DIR / f"mbo_{date}.npz",
        DATA_DIR / f"book_{date}.npz",
        DATA_DIR / f"{date}" / "data.npz",
    ]
    data_file = next((p for p in candidates if p.exists()), None)

    if data_file is None:
        print(f"[signal_gen] WARNING: no data file for date {date} in {DATA_DIR}", flush=True)
        continue

    print(f"[signal_gen] Processing {date} from {data_file.name}", flush=True)
    data = np.load(str(data_file), allow_pickle=True)

    # Attempt to load standard arrays; fall back to zeros where missing
    prices    = data["prices"]    if "prices"    in data else data.get("mid", np.zeros(1))
    volumes   = data["volumes"]   if "volumes"   in data else np.ones(len(prices))
    bid_book  = data["bids"]      if "bids"      in data else None
    ask_book  = data["asks"]      if "asks"      in data else None
    timestamps = data["timestamps"] if "timestamps" in data else np.arange(len(prices))

    n = len(prices)
    signals = np.zeros(n, dtype=np.float32)

    for i in range(LOOKBACK_BARS, n):
        sig = 0.0

        if STRATEGY in ("book_imbalance", "combined") and bid_book is not None:
            bids_i = bid_book[i] if bid_book.ndim == 3 else bid_book
            asks_i = ask_book[i] if ask_book.ndim == 3 else ask_book
            sig += calc_book_imbalance(bids_i, asks_i, IMBALANCE_DEPTH)

        if STRATEGY in ("momentum", "combined"):
            sig += calc_momentum(prices[:i+1], MOMENTUM_WINDOW)

        if STRATEGY in ("vwap_reversion", "combined"):
            sig += calc_vwap_reversion(prices[:i+1], volumes[:i+1], LOOKBACK_BARS)

        signals[i] = sig

    # Apply side filter
    if SIDE == "long_only":
        signals = np.maximum(signals, 0)
    elif SIDE == "short_only":
        signals = np.minimum(signals, 0)

    # Normalize
    if NORMALIZE:
        max_abs = np.max(np.abs(signals)) + 1e-8
        signals = signals / max_abs

    # Threshold
    signals[np.abs(signals) < MIN_SIGNAL] = 0.0

    all_signals.append(signals)
    all_timestamps.append(timestamps)
    total_signals += int(np.sum(signals != 0))
    print(f"  {date}: {n} bars, {total_signals} signals generated", flush=True)

# Save combined output
if all_signals:
    combined_signals    = np.concatenate(all_signals,    axis=0)
    combined_timestamps = np.concatenate(all_timestamps, axis=0)
    np.savez_compressed(
        str(OUTPUT_PATH),
        signals=combined_signals,
        timestamps=combined_timestamps,
        dates=np.array(DATES, dtype="U10"),
        strategy=np.array([STRATEGY]),
    )
    print(f"[signal_gen] Saved {len(combined_signals)} rows to {OUTPUT_PATH}", flush=True)
else:
    print("[signal_gen] WARNING: no signals produced", flush=True)

result = {
    "total_signals": total_signals,
    "total_bars":    sum(len(s) for s in all_signals),
    "dates":         DATES,
    "strategy":      STRATEGY,
    "output_path":   str(OUTPUT_PATH),
}
print(f"RESULT: {json.dumps(result)}", flush=True)
`;

// ─── 3. model_training ────────────────────────────────────────────────────
TEMPLATES.model_training = `#!/usr/bin/env python3
"""
BookSpatialCNN training script — generated by QCC Script Factory
Template: model_training

Params:
  model_name       : identifier string (e.g. "wider_cnn_v2")
  architecture     : "BookSpatialCNN" | "BookSpatialCNNWide" | "BookSpatialCNNDeep"
  data_dir         : root data directory on this node
  output_dir       : where to save model weights + predictions
  horizon_bars     : prediction horizon in bars (default 100)
  subsample        : subsample every Nth bar during training (default 5)
  window_mode      : "expanding" | "sliding"
  max_train_days   : max calendar days of training data per fold (default 30)
  epochs           : training epochs per fold (default 3)
  batch_size       : batch size (default 512)
  lr               : learning rate (default 3e-4)
  dropout          : dropout rate (default 0.1)
  conv_channels    : list of conv layer channel widths for custom arch
  fc_dims          : list of fully-connected layer widths
  num_folds        : number of walk-forward folds (default -1 = auto from data)
  start_fold       : first fold index to train (0-based, for warm-start resume)
  save_npz         : save .npz prediction files per fold (default True)
"""
import sys, os, json, time

# ── Path bootstrap ────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LVL3_ROOT  = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
if LVL3_ROOT not in sys.path:
    sys.path.insert(0, LVL3_ROOT)

# ── Params ────────────────────────────────────────────────────────────────
MODEL_NAME      = "{{model_name|book_spatial_cnn}}"
ARCHITECTURE    = "{{architecture|BookSpatialCNN}}"
DATA_DIR        = "{{data_dir}}"
OUTPUT_DIR      = "{{output_dir}}"
HORIZON_BARS    = {{horizon_bars|100}}
SUBSAMPLE       = {{subsample|5}}
WINDOW_MODE     = "{{window_mode|expanding}}"
MAX_TRAIN_DAYS  = {{max_train_days|30}}
EPOCHS          = {{epochs|3}}
BATCH_SIZE      = {{batch_size|512}}
LR              = {{lr|3e-4}}
DROPOUT         = {{dropout|0.1}}
CONV_CHANNELS   = {{conv_channels|[32, 64, 128]}}
FC_DIMS         = {{fc_dims|[256, 128]}}
NUM_FOLDS       = {{num_folds|-1}}
START_FOLD      = {{start_fold|0}}
SAVE_NPZ        = {{save_npz|True}}

os.makedirs(OUTPUT_DIR, exist_ok=True)

import torch
import numpy as np

try:
    from models.book_spatial_cnn import BookSpatialCNN, BookSpatialCNNWide, BookSpatialCNNDeep
    from training.walk_forward   import WalkForwardTrainer
    from training.data_loader    import BookDataLoader
except ImportError as e:
    print(f"[training] Import error: {e}", flush=True)
    print(f"  sys.path: {sys.path[:3]}", flush=True)
    sys.exit(1)

ARCH_MAP = {
    "BookSpatialCNN":      BookSpatialCNN,
    "BookSpatialCNNWide":  BookSpatialCNNWide,
    "BookSpatialCNNDeep":  BookSpatialCNNDeep,
}
ModelClass = ARCH_MAP.get(ARCHITECTURE)
if ModelClass is None:
    print(f"[training] Unknown architecture: {ARCHITECTURE}", flush=True)
    sys.exit(1)

model_kwargs = dict(
    conv_channels=CONV_CHANNELS,
    fc_dims=FC_DIMS,
    dropout=DROPOUT,
)

print(f"[training] Starting {MODEL_NAME} ({ARCHITECTURE})", flush=True)
print(f"  data_dir={DATA_DIR}  output_dir={OUTPUT_DIR}", flush=True)
print(f"  horizon={HORIZON_BARS}  subsample={SUBSAMPLE}  window={WINDOW_MODE}", flush=True)
print(f"  epochs={EPOCHS}  batch_size={BATCH_SIZE}  lr={LR}", flush=True)

loader  = BookDataLoader(DATA_DIR, horizon_bars=HORIZON_BARS, subsample=SUBSAMPLE)
trainer = WalkForwardTrainer(
    model_class=ModelClass,
    model_kwargs=model_kwargs,
    data_loader=loader,
    output_dir=OUTPUT_DIR,
    window_mode=WINDOW_MODE,
    max_train_days=MAX_TRAIN_DAYS,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    lr=LR,
    save_npz=SAVE_NPZ,
)

fold_results = []
folds = trainer.get_folds()
if NUM_FOLDS > 0:
    folds = folds[:NUM_FOLDS]
if START_FOLD > 0:
    folds = folds[START_FOLD:]

for fold_idx, fold in enumerate(folds, start=START_FOLD):
    t0 = time.time()
    print(f"[training] === Fold {fold_idx} ===", flush=True)
    metrics = trainer.train_fold(fold_idx, fold)
    elapsed = time.time() - t0

    ic  = metrics.get("ic", None)
    vl  = metrics.get("val_loss", None)
    tl  = metrics.get("train_loss", None)

    print(
        f"  fold={fold_idx}  ic={ic:.4f}  val_loss={vl:.4f}  train_loss={tl:.4f}  time={elapsed:.0f}s",
        flush=True,
    )
    fold_results.append({
        "fold":       fold_idx,
        "ic":         ic,
        "val_loss":   vl,
        "train_loss": tl,
        "epoch_time_sec": elapsed / max(EPOCHS, 1),
        "duration_sec":   elapsed,
    })

mean_ic = float(np.mean([r["ic"] for r in fold_results if r["ic"] is not None])) if fold_results else None
best_ic = float(np.max([r["ic"] for r in fold_results if r["ic"] is not None]))  if fold_results else None

summary = {
    "model_name":  MODEL_NAME,
    "architecture": ARCHITECTURE,
    "folds":       fold_results,
    "mean_ic":     mean_ic,
    "best_ic":     best_ic,
    "ic":          mean_ic,   # alias for orchestrator auto-harvest
    "total_folds": len(fold_results),
    "epochs":      EPOCHS,
    "output_dir":  OUTPUT_DIR,
}
print(f"RESULT: {json.dumps(summary)}", flush=True)
print(f"[training] Done. mean_ic={mean_ic}  best_ic={best_ic}", flush=True)
`;

// ─── 4. analysis ───────────────────────────────────────────────────────────
TEMPLATES.analysis = `#!/usr/bin/env python3
"""
Analysis script — generated by QCC Script Factory
Template: analysis

Params:
  analysis_type  : "ic_computation" | "pnl_breakdown" | "monte_carlo" | "all"
  input_dir      : directory containing prediction NPZ files or results JSON
  output_dir     : directory to write analysis output
  dates          : list of YYYYMMDD strings to include (empty = all in input_dir)
  mc_iterations  : Monte Carlo iterations for significance testing (default 1000)
  ic_lag         : forward lag for IC computation in bars (default 1)
  resample_freq  : PnL breakdown resampling frequency — "daily" | "weekly" | "monthly"
  model_name     : model identifier (for labelling output)
"""
import numpy as np
import json, os, sys, random
from pathlib import Path
from datetime import datetime

ANALYSIS_TYPE  = "{{analysis_type|all}}"
INPUT_DIR      = Path("{{input_dir}}")
OUTPUT_DIR     = Path("{{output_dir|.}}")
DATES          = {{dates|[]}}
MC_ITERATIONS  = {{mc_iterations|1000}}
IC_LAG         = {{ic_lag|1}}
RESAMPLE_FREQ  = "{{resample_freq|daily}}"
MODEL_NAME     = "{{model_name|unknown}}"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Load prediction files ─────────────────────────────────────────────────
npz_files = sorted(INPUT_DIR.glob("*.npz"))
if DATES:
    npz_files = [f for f in npz_files if any(d in f.name for d in DATES)]

print(f"[analysis] Found {len(npz_files)} NPZ files in {INPUT_DIR}", flush=True)

all_preds  = []
all_labels = []

for npz_file in npz_files:
    try:
        data   = np.load(str(npz_file), allow_pickle=True)
        preds  = data["predictions"] if "predictions" in data else data.get("signals", None)
        labels = data["labels"]      if "labels"      in data else data.get("targets", None)
        if preds is None or labels is None:
            print(f"  SKIP {npz_file.name}: missing predictions or labels", flush=True)
            continue
        all_preds.append(preds.flatten())
        all_labels.append(labels.flatten())
    except Exception as e:
        print(f"  ERROR loading {npz_file.name}: {e}", flush=True)

result = {
    "model_name":    MODEL_NAME,
    "analysis_type": ANALYSIS_TYPE,
    "n_files":       len(npz_files),
}

if not all_preds:
    print("[analysis] No data loaded — check input_dir and NPZ format", flush=True)
    print(f"RESULT: {json.dumps(result)}", flush=True)
    sys.exit(0)

preds  = np.concatenate(all_preds)
labels = np.concatenate(all_labels)
n      = len(preds)
print(f"[analysis] Loaded {n} prediction-label pairs", flush=True)

# ── IC Computation ────────────────────────────────────────────────────────
def compute_ic(p, l):
    """Pearson IC between predictions and lagged labels."""
    p_lag = p[:-IC_LAG]
    l_lag = l[IC_LAG:]
    if len(p_lag) < 2:
        return float("nan")
    corr = np.corrcoef(p_lag, l_lag)[0, 1]
    return float(corr) if np.isfinite(corr) else 0.0

if ANALYSIS_TYPE in ("ic_computation", "all"):
    ic = compute_ic(preds, labels)
    # Daily IC breakdown
    daily_ics = []
    for npz_file in npz_files[:30]:  # cap at 30 for speed
        try:
            d = np.load(str(npz_file), allow_pickle=True)
            p = d["predictions"] if "predictions" in d else d.get("signals", None)
            l = d["labels"]      if "labels"      in d else d.get("targets", None)
            if p is not None and l is not None:
                daily_ics.append(compute_ic(p.flatten(), l.flatten()))
        except Exception:
            pass

    result["ic"]             = round(ic, 6)
    result["daily_ic_mean"]  = round(float(np.nanmean(daily_ics)), 6)  if daily_ics else None
    result["daily_ic_std"]   = round(float(np.nanstd(daily_ics)),  6)  if daily_ics else None
    result["positive_days"]  = int(sum(x > 0 for x in daily_ics))      if daily_ics else None
    result["total_days"]     = len(daily_ics)
    print(f"  IC={ic:.4f}  daily_mean={result['daily_ic_mean']}  pos_days={result['positive_days']}/{result['total_days']}", flush=True)

# ── PnL Breakdown ─────────────────────────────────────────────────────────
if ANALYSIS_TYPE in ("pnl_breakdown", "all"):
    # Simplified PnL proxy: long when pred > 0, short when pred < 0
    signs   = np.sign(preds[:-IC_LAG])
    rets    = labels[IC_LAG:]
    pnl_per_bar = signs * rets

    # Remove zeros (flat bars)
    active  = pnl_per_bar[pnl_per_bar != 0]
    total_pnl    = float(np.sum(active))
    win_rate     = float(np.mean(active > 0)) if len(active) > 0 else 0.0
    avg_win      = float(np.mean(active[active > 0])) if np.any(active > 0) else 0.0
    avg_loss     = float(np.mean(active[active < 0])) if np.any(active < 0) else 0.0
    profit_factor = abs(avg_win / avg_loss) if avg_loss != 0 else float("inf")
    sharpe        = float(np.mean(active) / (np.std(active) + 1e-8) * np.sqrt(252 * 390)) if len(active) > 0 else 0.0

    result["pnl"]           = round(total_pnl, 4)
    result["win_rate"]      = round(win_rate, 4)
    result["avg_win"]       = round(avg_win, 6)
    result["avg_loss"]      = round(avg_loss, 6)
    result["profit_factor"] = round(profit_factor, 4) if np.isfinite(profit_factor) else None
    result["sharpe"]        = round(sharpe, 4)
    result["trades"]        = int(len(active))
    print(f"  pnl={total_pnl:.4f}  sharpe={sharpe:.3f}  win_rate={win_rate:.1%}  trades={len(active)}", flush=True)

# ── Monte Carlo ───────────────────────────────────────────────────────────
if ANALYSIS_TYPE in ("monte_carlo", "all") and "ic" in result:
    observed_ic = result["ic"]
    # Permutation test: shuffle labels MC_ITERATIONS times and recompute IC
    null_ics = []
    shuffled = labels.copy()
    for _ in range(MC_ITERATIONS):
        np.random.shuffle(shuffled)
        null_ics.append(compute_ic(preds, shuffled))

    null_ics = np.array(null_ics)
    p_value  = float(np.mean(null_ics >= observed_ic))
    result["mc_p_value"]       = round(p_value, 4)
    result["mc_iterations"]    = MC_ITERATIONS
    result["monte_carlo_passed"] = bool(p_value < 0.05)
    print(f"  Monte Carlo: p_value={p_value:.4f}  passed={result['monte_carlo_passed']}", flush=True)

# ── Save output ───────────────────────────────────────────────────────────
out_file = OUTPUT_DIR / f"analysis_{MODEL_NAME}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
with open(out_file, "w") as f:
    json.dump(result, f, indent=2)
print(f"[analysis] Results saved to {out_file}", flush=True)

print(f"RESULT: {json.dumps(result)}", flush=True)
`;

// ─── Public API ────────────────────────────────────────────────────────────

/**
 * List all available template names.
 */
function listTemplates() {
  return Object.keys(TEMPLATES);
}

/**
 * Generate a complete Python script string from a template name and parameter map.
 *
 * @param {string} templateName  — one of listTemplates()
 * @param {object} params        — key-value pairs matching {{placeholders}} in the template
 * @returns {string}             — fully rendered Python script
 */
function generateScript(templateName, params = {}) {
  const tpl = TEMPLATES[templateName];
  if (!tpl) {
    throw new Error(`Unknown template "${templateName}". Available: ${listTemplates().join(', ')}`);
  }
  return fillTemplate(tpl, params);
}

/**
 * Deploy a script to a remote node by writing it locally then uploading via
 * Python paramiko (reuses the same SFTP mechanism as the rest of the codebase).
 *
 * For Neptune (localhost / windows) we skip SFTP and write directly to the
 * local Lvl3Quant scripts directory.
 *
 * @param {string} scriptContent — Python source to upload
 * @param {string} nodeName      — target node (must exist in QCC DB or remote_servers.json)
 * @param {string} remotePath    — absolute path on the remote node where the file should land
 * @returns {string}             — the remotePath (confirmed)
 */
async function deployScript(scriptContent, nodeName, remotePath) {
  if (!_db) throw new Error('ScriptFactory.init(db) must be called before deployScript');

  // Ensure consistent line endings for the platform (Windows nodes prefer CRLF but Python handles LF fine)
  const normalized = scriptContent.replace(/\r\n/g, '\n');

  // ── Neptune / localhost: direct filesystem write ──────────────────────
  if (nodeName.toLowerCase() === 'neptune') {
    fs.writeFileSync(remotePath, normalized, 'utf8');
    console.log(`[ScriptFactory] Written directly to Neptune: ${remotePath}`);
    return remotePath;
  }

  // ── Remote nodes: SFTP via Python paramiko ───────────────────────────
  // Write the script to a temp local file, then upload via a Python SFTP helper.
  // We write the SFTP helper itself to a second temp file to avoid any shell
  // quoting / newline issues with -c inline scripts.
  const stamp    = Date.now();
  const tmpLocal = path.join(LOCAL_SCRIPTS, `_factory_payload_${stamp}.py`);
  const tmpSftp  = path.join(LOCAL_SCRIPTS, `_factory_sftp_${stamp}.py`);

  // Build path strings safe for Python raw-string literals (forward slashes)
  const pyBasePath  = BASE_DIR.replace(/\\/g, '/');
  const pyLocalSrc  = tmpLocal.replace(/\\/g, '/');
  const pyRemoteDst = remotePath.replace(/\\/g, '/');

  const sftpScript = [
    'import sys, os',
    `sys.path.insert(0, r"${pyBasePath}")`,
    'from utils.ssh_exec import load_config',
    'import paramiko',
    '',
    'cfg = load_config()',
    `srv = cfg["servers"].get("${nodeName}")`,
    'if not srv:',
    `    print("ERROR: server '${nodeName}' not in remote_servers.json", file=sys.stderr)`,
    '    sys.exit(1)',
    '',
    'host     = srv.get("tailscale_ip") or srv["host"]',
    'user     = srv["user"]',
    'passwd   = srv.get("password", "")',
    'port     = int(srv.get("port", 22))',
    'key_file = srv.get("key_file", "")',
    '',
    'client = paramiko.SSHClient()',
    'client.set_missing_host_key_policy(paramiko.AutoAddPolicy())',
    'kwargs = dict(hostname=host, port=port, username=user,',
    '              timeout=30, allow_agent=False, look_for_keys=False)',
    '',
    '# Prefer key auth when key_file is set and readable',
    'resolved_key = os.path.expanduser(key_file) if key_file else ""',
    'if resolved_key and os.path.exists(resolved_key):',
    '    try:',
    '        kwargs["pkey"] = paramiko.Ed25519Key.from_private_key_file(resolved_key)',
    '    except Exception:',
    '        try:',
    '            kwargs["pkey"] = paramiko.RSAKey.from_private_key_file(resolved_key)',
    '        except Exception:',
    '            kwargs["password"] = passwd',
    'else:',
    '    kwargs["password"] = passwd',
    '',
    'client.connect(**kwargs)',
    'sftp = client.open_sftp()',
    '',
    `local_src  = r"${pyLocalSrc}"`,
    `remote_dst = r"${pyRemoteDst}"`,
    '',
    '# Ensure remote parent directory exists (best-effort mkdir -p)',
    'remote_dir = remote_dst.replace("\\\\", "/").rsplit("/", 1)[0]',
    'def sftp_makedirs(sftp, d):',
    '    parts = d.lstrip("/").split("/")',
    '    cur = "/" if d.startswith("/") else ""',
    '    for p in parts:',
    '        if not p:',
    '            continue',
    '        cur = (cur + "/" + p).replace("//", "/")',
    '        try:',
    '            sftp.stat(cur)',
    '        except FileNotFoundError:',
    '            try:',
    '                sftp.mkdir(cur)',
    '            except Exception:',
    '                pass',
    'sftp_makedirs(sftp, remote_dir)',
    '',
    'sftp.put(local_src, remote_dst)',
    'sftp.close()',
    'client.close()',
    `print(f"OK: uploaded to ${nodeName}:{remote_dst}")`,
  ].join('\n');

  try {
    fs.writeFileSync(tmpLocal, normalized, 'utf8');
    fs.writeFileSync(tmpSftp,  sftpScript,  'utf8');

    const pyCmd = process.platform === 'win32' ? 'python' : 'python3';
    const result = execSync(
      `${pyCmd} "${tmpSftp}"`,
      { encoding: 'utf8', timeout: 60000, windowsHide: true }
    );
    console.log(`[ScriptFactory] SFTP upload: ${result.trim()}`);
    return remotePath;
  } finally {
    try { fs.unlinkSync(tmpLocal); } catch (_) {}
    try { fs.unlinkSync(tmpSftp);  } catch (_) {}
  }
}

/**
 * Resolve the remote absolute path for a generated script on a given node.
 *
 * Convention: <lvl3_root>/scripts/<scriptName>
 *
 * @param {string} scriptName  — filename (e.g. "fillsim_sweep_20250106.py")
 * @param {string} nodeName
 * @returns {string}
 */
function resolveRemotePath(scriptName, nodeName) {
  if (!_db) throw new Error('ScriptFactory.init(db) must be called before resolveRemotePath');

  const node = _db.getNode(nodeName);
  if (!node) throw new Error(`Node "${nodeName}" not found in QCC database`);

  const root    = node.lvl3_root;
  const isWin   = (node.os || '').toLowerCase() === 'windows';
  const sep     = isWin ? '\\' : '/';
  return `${root}${sep}${REMOTE_SCRIPTS_SUBDIR}${sep}${scriptName}`;
}

/**
 * Generate a descriptive script filename based on template and key params.
 */
function makeScriptName(templateName, params) {
  const ts    = new Date().toISOString().replace(/[:.]/g, '').slice(0, 15); // YYYYMMDDTHHmmss
  const label = params.model_name || params.strategy || templateName;
  const slug  = label.replace(/[^a-z0-9_]/gi, '_').toLowerCase();
  return `factory_${slug}_${ts}.py`;
}

/**
 * All-in-one: generate script, deploy to node, enqueue in research_queue.
 *
 * @param {string}  templateName  — template to use
 * @param {object}  params        — template parameters
 * @param {string}  nodeName      — target compute node
 * @param {number}  [priority=5] — queue priority (1=highest, 10=lowest)
 * @param {object}  [options]     — extra options:
 *   - dependsOn {number}         — research_queue ID this experiment depends on
 *   - tags {string[]}            — additional tags
 *   - description {string}       — human-readable description override
 *   - jobType {string}           — override job_type in config_json
 *   - requiresGpu {boolean}      — override requires_gpu
 *   - maxRetries {number}        — max retry count (default 2)
 *   - skipDeploy {boolean}       — skip SFTP upload (e.g. script already on node)
 *
 * @returns {Promise<number>}     — the new research_queue experiment ID
 */
async function createAndQueueExperiment(templateName, params = {}, nodeName, priority = 5, options = {}) {
  if (!_db) throw new Error('ScriptFactory.init(db) must be called before createAndQueueExperiment');

  // 1. Generate script
  const scriptContent = generateScript(templateName, params);

  // 2. Determine remote path
  const scriptName   = makeScriptName(templateName, params);
  const remotePath   = resolveRemotePath(scriptName, nodeName);

  // 3. Deploy (unless caller opts out)
  if (!options.skipDeploy) {
    await deployScript(scriptContent, nodeName, remotePath);
  }

  // 4. Derive job_type and requires_gpu from template if not overridden
  const TEMPLATE_JOB_TYPES = {
    fillsim_sweep:       { job_type: 'fillsim',  requires_gpu: false },
    strategy_signal_gen: { job_type: 'sweep',    requires_gpu: false },
    model_training:      { job_type: 'training', requires_gpu: true  },
    analysis:            { job_type: 'other',    requires_gpu: false },
  };
  const defaults = TEMPLATE_JOB_TYPES[templateName] || { job_type: 'other', requires_gpu: false };
  const jobType    = options.jobType    ?? defaults.job_type;
  const requiresGpu = options.requiresGpu ?? defaults.requires_gpu;

  // 5. Build default tags
  const baseTags = [templateName];
  if (params.model_name)  baseTags.push(params.model_name);
  if (params.strategy)    baseTags.push(params.strategy);
  if (options.tags && Array.isArray(options.tags)) baseTags.push(...options.tags);

  // 6. Build a readable name
  const label = params.model_name || params.strategy || templateName;
  const expName = `[factory] ${label} on ${nodeName}`;

  // 7. Enqueue
  const { addExperiment } = _getOrchestratorHelpers();
  const result = addExperiment({
    name:        expName,
    description: options.description || `Auto-generated ${templateName} experiment`,
    script_path: remotePath,
    node:        nodeName,
    priority,
    config_json: {
      job_type:     jobType,
      requires_gpu: requiresGpu,
      template:     templateName,
      params,
      // Pass params also as CLI args for simple scripts that accept --key value
      params: params,
    },
    depends_on:  options.dependsOn || null,
    tags:        baseTags,
    max_retries: options.maxRetries !== undefined ? options.maxRetries : 2,
  });

  console.log(`[ScriptFactory] Queued experiment #${result.id}: ${expName}`);
  return result.id;
}

/**
 * Suggest follow-up experiments based on a completed experiment's result.
 *
 * Returns an array of suggestion objects:
 *   { template, params, node, priority, dependsOn, reason }
 *
 * The caller decides whether to act on them.
 *
 * @param {object} completedExp  — research_queue row
 * @param {object} parsedResult  — parsed result JSON from that experiment
 * @returns {Array}
 */
function suggestFollowUp(completedExp, parsedResult) {
  const suggestions = [];
  if (!completedExp || !parsedResult) return suggestions;

  const config = completedExp.config_json
    ? (typeof completedExp.config_json === 'string'
        ? JSON.parse(completedExp.config_json)
        : completedExp.config_json)
    : {};
  const template = config.template || '';
  const params   = config.params   || {};
  const node     = completedExp.node;

  // ── Rule 1: strategy_signal_gen → fillsim_sweep ───────────────────────
  // If signal gen produced a meaningful number of signals, auto-queue a fill sim
  if (template === 'strategy_signal_gen') {
    const total = parsedResult.total_signals || 0;
    if (total >= 10000) {
      const outputPath = parsedResult.output_path;
      if (outputPath) {
        // Find fill_sim_cli path for the target node from remote_servers.json
        let fillSimCli = _getFillSimCli(node);
        suggestions.push({
          template:  'fillsim_sweep',
          node,
          priority:  completedExp.priority,   // same priority as parent
          dependsOn: completedExp.id,
          reason:    `signal_gen produced ${total} signals (≥10K threshold) — queue fill sim`,
          params: {
            dates:          params.dates || [],
            signal_sources: [outputPath],
            fill_sim_cli:   fillSimCli,
            output_dir:     outputPath.replace(/\.npz$/, '_fillsim'),
            tp_ticks:       [3, 4, 5, 6],
            sl_ticks:       [2, 3, 4],
            trailing_ticks: [0, 2],
            hold_ms:        [5000, 10000, 30000],
          },
        });
      }
    } else {
      // Low signal count — suggest re-running with a lower min_signal threshold
      const currentMin = parseFloat(params.min_signal || 0.01);
      if (currentMin > 0.001) {
        suggestions.push({
          template:  'strategy_signal_gen',
          node,
          priority:  completedExp.priority + 1,
          dependsOn: null,
          reason:    `only ${total} signals (<10K) — retry with lower min_signal`,
          params: {
            ...params,
            min_signal: +(currentMin / 2).toFixed(4),
          },
        });
      }
    }
  }

  // ── Rule 2: model_training → analysis (always after training) ─────────
  if (template === 'model_training') {
    const meanIC  = parsedResult.mean_ic || parsedResult.ic || null;
    const outDir  = parsedResult.output_dir || params.output_dir || null;

    if (outDir) {
      suggestions.push({
        template:  'analysis',
        node,
        priority:  completedExp.priority + 1,
        dependsOn: completedExp.id,
        reason:    `model training complete (mean_ic=${meanIC}) — run IC/PnL/MC analysis`,
        params: {
          analysis_type: 'all',
          input_dir:     outDir,
          output_dir:    outDir + '_analysis',
          model_name:    params.model_name || 'model',
          mc_iterations: 1000,
        },
      });
    }

    // Rule 2b: if IC improved substantially, also queue a fillsim sweep
    // (assuming predictions NPZ files are in output_dir)
    if (meanIC !== null && meanIC > 0.05) {
      const fillSimCli = _getFillSimCli(node);
      if (outDir) {
        suggestions.push({
          template:  'fillsim_sweep',
          node:      _pickFillSimNode(node),
          priority:  completedExp.priority + 2,
          dependsOn: completedExp.id,
          reason:    `IC=${meanIC.toFixed(4)} exceeds 0.05 threshold — validate with fill sim`,
          params: {
            dates:          params.dates || [],
            signal_sources: [outDir],  // fill_sim_cli can accept a dir of NPZ predictions
            fill_sim_cli:   fillSimCli,
            output_dir:     outDir + '_fillsim',
            tp_ticks:       [3, 4, 5],
            sl_ticks:       [2, 3],
            hold_ms:        [10000],
          },
        });
      }
    }
  }

  // ── Rule 3: fillsim_sweep → analysis ─────────────────────────────────
  // Always run a PnL breakdown analysis after a fill sim sweep
  if (template === 'fillsim_sweep') {
    const outDir = params.output_dir || null;
    if (outDir) {
      suggestions.push({
        template:  'analysis',
        node:      _pickCPUNode(node),
        priority:  completedExp.priority + 1,
        dependsOn: completedExp.id,
        reason:    `fillsim complete (${parsedResult.total_runs} runs) — run PnL breakdown`,
        params: {
          analysis_type: 'pnl_breakdown',
          input_dir:     outDir,
          output_dir:    outDir + '_analysis',
          model_name:    params.model_name || 'fillsim',
        },
      });
    }
  }

  // ── Rule 4: analysis with positive MC → re-queue fillsim at higher confidence ─
  if (template === 'analysis') {
    const mcPassed = parsedResult.monte_carlo_passed;
    const ic       = parsedResult.ic || 0;
    if (mcPassed && ic > 0.03) {
      suggestions.push({
        template:  'analysis',
        node:      _pickCPUNode(node),
        priority:  completedExp.priority,
        dependsOn: completedExp.id,
        reason:    `MC passed (p<0.05), IC=${ic} — re-run with more iterations for publication-quality stats`,
        params: {
          ...params,
          analysis_type:  'monte_carlo',
          mc_iterations:  10000,
          model_name:     (params.model_name || '') + '_highconf',
        },
      });
    }
  }

  return suggestions;
}

// ─── Internal helpers ──────────────────────────────────────────────────────

/**
 * Get orchestrator's addExperiment function.
 * The orchestrator may import the factory, or the factory may run standalone.
 * We use a lazy require to avoid circular imports.
 */
function _getOrchestratorHelpers() {
  // When the factory is imported by the orchestrator, addExperiment is passed
  // via init() as a second argument. If it wasn't, fall back to a direct DB insert.
  if (_addExperimentFn) return { addExperiment: _addExperimentFn };

  // Direct DB insert fallback (mirrors orchestrator's addExperiment logic)
  return {
    addExperiment: (data) => {
      const stmt = _db.db.prepare(`
        INSERT INTO research_queue (name, description, script_path, node, priority, config_json, depends_on, tags, max_retries)
        VALUES (@name, @description, @script_path, @node, @priority, @config_json, @depends_on, @tags, @max_retries)
      `);
      const result = stmt.run({
        name:        data.name,
        description: data.description || null,
        script_path: data.script_path,
        node:        data.node,
        priority:    data.priority || 5,
        config_json: data.config_json ? JSON.stringify(data.config_json) : null,
        depends_on:  data.depends_on || null,
        tags:        Array.isArray(data.tags) ? data.tags.join(',') : (data.tags || null),
        max_retries: data.max_retries !== undefined ? data.max_retries : 2,
      });
      return { id: Number(result.lastInsertRowid) };
    },
  };
}

let _addExperimentFn = null;

/**
 * Optional: allow the orchestrator to inject its own addExperiment so the factory
 * triggers the same logging/notification paths.
 */
function setAddExperimentFn(fn) {
  _addExperimentFn = fn;
}

/** Load fill_sim_cli path for a node from remote_servers.json */
function _getFillSimCli(nodeName) {
  try {
    const cfg = JSON.parse(fs.readFileSync(SERVERS_CONFIG, 'utf8'));
    const srv = cfg.servers?.[nodeName];
    if (srv?.fill_sim_cli) return srv.fill_sim_cli;
  } catch (_) {}
  // Fallback conventions by node
  const defaults = {
    razer:   'C:\\Users\\claude\\Documents\\Lvl3Quant\\rust_cache_builder\\target\\release\\fill_sim_cli.exe',
    neptune: 'C:\\Users\\Footb\\Documents\\Github\\Lvl3Quant\\rust_cache_builder\\target\\release\\fill_sim_cli.exe',
    uranus:  'C:\\Users\\nick\\Lvl3Quant\\rust_cache_builder\\target\\release\\fill_sim_cli.exe',
    jupiter: '/home/jupiter/Lvl3Quant/rust_cache_builder/target/release/fill_sim_cli',
  };
  return defaults[nodeName] || 'fill_sim_cli';
}

/**
 * Pick the best node for a fill-sim (CPU task).
 * Prefer Jupiter, else fall back to the completed experiment's node.
 */
function _pickFillSimNode(currentNode) {
  return 'jupiter';   // Jupiter is the designated fill-sim hub
}

/**
 * Pick the best node for a CPU-only analysis task.
 * Prefer Jupiter, then Neptune.
 */
function _pickCPUNode(currentNode) {
  if (_db) {
    try {
      const jupiter = _db.getNode('jupiter');
      if (jupiter && jupiter.status !== 'offline') return 'jupiter';
    } catch (_) {}
  }
  return currentNode || 'neptune';
}

// ─── Module exports ────────────────────────────────────────────────────────

module.exports = {
  // Setup
  init,
  setAddExperimentFn,

  // Core API
  listTemplates,
  generateScript,
  deployScript,
  resolveRemotePath,
  makeScriptName,
  createAndQueueExperiment,

  // Follow-up logic
  suggestFollowUp,

  // Exposed for testing
  fillTemplate,
  _getFillSimCli,
};
