'use strict';
/**
 * session_logger.js — Daily session log system for the memory bridge.
 *
 * Creates/appends to memory/sessions/YYYY-MM-DD.md for each calendar day.
 * Provides structured logging of milestones, results, decisions, and errors.
 *
 * FORMAT (markdown, human-readable and machine-searchable):
 *
 *   ## 2026-02-25
 *
 *   ### 07:30 — Session Start
 *   - Checked pending: 16 urgent items
 *   - PC restarted, all compute dead
 *   - Server: 4 DL jobs survived
 *
 *   ### 08:23 — BookSpatialCNN Restarted
 *   - PID 33392, fold 1/64, batch-128, subsample-5
 *   - GPU: 92%, 4.2GB VRAM
 *
 * USAGE:
 *   const logger = require('./utils/session_logger');
 *   logger.logMilestone('BookSpatialCNN fold 5 complete, IC=0.178');
 *   logger.logResult('30s rl_reward', { sharpe: 1.02, status: 'CLEAN' });
 *   logger.logDecision('Discard Sharpe 20 results', 'Fill bug: 97% vs 3% fill rate');
 *   logger.logError('SSH timeout on YOUR_JUPITER_LAN_IP', 'port 22 refused');
 *
 * PRE-COMPACTION: Call logger.flush() before context compresses to save state.
 */

const fs = require('fs');
const path = require('path');

// Memory directory location
const MEMORY_DIR = path.join(
  process.env.USERPROFILE || process.env.HOME || '',
  '.claude',
  'projects',
  'C--Users-YOUR_USERNAME-Documents-Github-teleclaude-main',
  'memory'
);

const SESSIONS_DIR = path.join(MEMORY_DIR, 'sessions');

/**
 * Get current date string YYYY-MM-DD in local time.
 * @returns {string}
 */
function getDateStr() {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

/**
 * Get current time string HH:MM in local time.
 * @returns {string}
 */
function getTimeStr() {
  const now = new Date();
  const h = String(now.getHours()).padStart(2, '0');
  const m = String(now.getMinutes()).padStart(2, '0');
  return `${h}:${m}`;
}

/**
 * Get the path for today's session log file.
 * @param {string} [dateStr] - Override date (YYYY-MM-DD), defaults to today
 * @returns {string}
 */
function getSessionFilePath(dateStr) {
  const date = dateStr || getDateStr();
  return path.join(SESSIONS_DIR, `${date}.md`);
}

/**
 * Ensure the sessions directory exists, creating it if needed.
 */
function ensureSessionsDir() {
  if (!fs.existsSync(SESSIONS_DIR)) {
    fs.mkdirSync(SESSIONS_DIR, { recursive: true });
  }
}

/**
 * Ensure today's session file exists with a date header.
 * @param {string} filePath
 */
function ensureSessionFile(filePath) {
  ensureSessionsDir();
  if (!fs.existsSync(filePath)) {
    const dateStr = getDateStr();
    const header = `# Session Log — ${dateStr}\n*Auto-generated by session_logger.js*\n\n---\n\n`;
    fs.writeFileSync(filePath, header, 'utf8');
  }
}

/**
 * Append a formatted block to today's session log.
 * @param {string} heading - Section heading (shown after time prefix)
 * @param {string[]} bullets - Array of bullet point strings (do not include "- " prefix)
 * @param {string} [dateStr] - Override date
 */
function appendBlock(heading, bullets, dateStr) {
  const filePath = getSessionFilePath(dateStr);
  ensureSessionFile(filePath);

  const time = getTimeStr();
  const lines = [`\n### ${time} — ${heading}`];
  for (const bullet of bullets) {
    lines.push(`- ${bullet}`);
  }
  lines.push(''); // trailing newline for readability

  fs.appendFileSync(filePath, lines.join('\n'), 'utf8');
}

/**
 * Log a session milestone — a notable event or state change.
 *
 * @param {string} text - Description of the milestone
 * @param {string[]} [details] - Optional additional detail lines
 * @example
 *   logMilestone('BookSpatialCNN fold 5 complete', ['IC=0.178', 'GPU: 94%']);
 */
function logMilestone(text, details = []) {
  appendBlock(text, details.length > 0 ? details : [text]);
}

/**
 * Log a strategy/model result.
 *
 * @param {string} strategy - Strategy or model name
 * @param {Object} result - Result data (key-value pairs to log)
 * @example
 *   logResult('30s rl_reward', { sharpe: 1.02, trades: 104, status: 'CLEAN' });
 */
function logResult(strategy, result) {
  const bullets = Object.entries(result).map(([k, v]) => `${k}: ${v}`);
  appendBlock(`Result — ${strategy}`, bullets);
}

/**
 * Log a decision made during the session.
 *
 * @param {string} decision - What was decided
 * @param {string} reason - Why this decision was made
 * @param {string[]} [alternatives] - Other options considered
 * @example
 *   logDecision('Discard Sharpe 20 results', 'Fill bug: 97% vs 3% fill rate');
 */
function logDecision(decision, reason, alternatives = []) {
  const bullets = [
    `Decision: ${decision}`,
    `Reason: ${reason}`,
    ...alternatives.map(a => `Alt considered: ${a}`),
  ];
  appendBlock(`Decision — ${decision}`, bullets);
}

/**
 * Log an error or unexpected state.
 *
 * @param {string} error - Error description
 * @param {string} [detail] - Additional context (stack trace excerpt, error code, etc.)
 * @param {string} [resolution] - How it was resolved (or "UNRESOLVED")
 * @example
 *   logError('SSH timeout on YOUR_JUPITER_LAN_IP', 'port 22 refused', 'Switched to LAN 192.168.1.100');
 */
function logError(error, detail = '', resolution = '') {
  const bullets = [
    `ERROR: ${error}`,
    ...(detail ? [`Detail: ${detail}`] : []),
    ...(resolution ? [`Resolution: ${resolution}`] : [`Resolution: UNRESOLVED`]),
  ];
  appendBlock(`Error — ${error}`, bullets);
}

/**
 * Log session start with context.
 *
 * @param {Object} [context] - Key-value context (e.g. { pending: '5 urgent', pcStatus: 'IDLE' })
 */
function logSessionStart(context = {}) {
  const bullets = [
    'Session started',
    ...Object.entries(context).map(([k, v]) => `${k}: ${v}`),
  ];
  appendBlock('Session Start', bullets);
}

/**
 * Log session end / pre-compaction flush.
 * Call this before context compression to preserve state.
 *
 * @param {string[]} [pendingItems] - Unfinished tasks to carry forward
 */
function logSessionEnd(pendingItems = []) {
  const bullets = [
    'Session ended / context flush',
    ...pendingItems.map(item => `PENDING: ${item}`),
  ];
  appendBlock('Session End / Flush', bullets);
}

/**
 * Log compute job status snapshot.
 *
 * @param {Object[]} jobs - Array of job status objects
 * @example
 *   logComputeSnapshot([
 *     { name: 'BookSpatialCNN', pid: 33392, status: 'fold 5/64', ic: 0.178 },
 *     { name: 'lstm_70d', location: 'Jupiter', status: 'fold 1/64' }
 *   ]);
 */
function logComputeSnapshot(jobs) {
  const bullets = jobs.map(j => {
    const parts = Object.entries(j).map(([k, v]) => `${k}=${v}`).join(', ');
    return parts;
  });
  appendBlock('Compute Snapshot', bullets);
}

/**
 * Read today's session log (or a specific date's log).
 *
 * @param {string} [dateStr] - Override date (YYYY-MM-DD), defaults to today
 * @returns {string} - Full content of the session log, or empty string if not found
 */
function readSession(dateStr) {
  const filePath = getSessionFilePath(dateStr);
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch (e) {
    return '';
  }
}

/**
 * List all session log files (most recent first).
 * @returns {string[]} - Array of date strings YYYY-MM-DD
 */
function listSessions() {
  ensureSessionsDir();
  try {
    const files = fs.readdirSync(SESSIONS_DIR)
      .filter(f => f.endsWith('.md') && /^\d{4}-\d{2}-\d{2}\.md$/.test(f))
      .map(f => f.replace('.md', ''))
      .sort()
      .reverse();
    return files;
  } catch (e) {
    return [];
  }
}

/**
 * Alias for logSessionEnd — for use in pre-compaction workflow.
 * Writes current state to session log before context is compressed.
 *
 * @param {string[]} pendingItems - Unfinished tasks
 */
const flush = logSessionEnd;

// CLI usage: node utils/session_logger.js <command> [args...]
if (require.main === module) {
  const args = process.argv.slice(2);
  const cmd = args[0];

  if (cmd === 'log' && args[1]) {
    logMilestone(args.slice(1).join(' '));
    console.log('Logged milestone.');
  } else if (cmd === 'error' && args[1]) {
    logError(args.slice(1).join(' '));
    console.log('Logged error.');
  } else if (cmd === 'read') {
    const content = readSession(args[1]);
    console.log(content || '(No session log found)');
  } else if (cmd === 'list') {
    const sessions = listSessions();
    console.log('Session logs:', sessions.join(', ') || '(none)');
  } else if (cmd === 'start') {
    logSessionStart();
    console.log('Session start logged.');
  } else {
    console.log('Usage:');
    console.log('  node utils/session_logger.js log <text>');
    console.log('  node utils/session_logger.js error <text>');
    console.log('  node utils/session_logger.js start');
    console.log('  node utils/session_logger.js read [YYYY-MM-DD]');
    console.log('  node utils/session_logger.js list');
  }
}

module.exports = {
  logMilestone,
  logResult,
  logDecision,
  logError,
  logSessionStart,
  logSessionEnd,
  logComputeSnapshot,
  readSession,
  listSessions,
  flush,
  getSessionFilePath,
  SESSIONS_DIR,
  MEMORY_DIR,
};
